version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: joomla_db
      MYSQL_USER: joomla_user
      MYSQL_PASSWORD: joomla_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  joomla:
    image: joomla:latest
    container_name: joomla
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:80"
    environment:
      JOOMLA_DB_HOST: mysql:3306
      JOOMLA_DB_USER: joomla_user
      JOOMLA_DB_PASSWORD: joomla_pass
      JOOMLA_DB_NAME: joomla_db
    volumes:
      - joomla_data:/var/www/html

volumes:
  mysql_data:
  joomla_data:
# This docker-compose file sets up a Joomla application with a MySQL database.